spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecom
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
ecom:
  amqp:
    rabbit:
      address: localhost:5672
      username: guest
      password: guest
      vhost: /
      exchange: Ecom-exchange
      queue: Ecom-product-queue
  product.img.location: ${HOME}/Downloads/practical-microservices-architectural-patterns-master/Christudas_Ch17_Source/ch17/ch17-01/Ax2-Ecom-No-Security/Ecom-xtra-setup/productImg/